### ISSUE TITLE
OSPL_URI warning obnoxious

### ISSUE THREAD

**Issue by paulbovbel** [ros2/rosidl_typesupport_opensplice#18]
----
#### Feature description
The warning implemented here (https://github.com/ros2/rosidl_typesupport_opensplice/blob/master/opensplice_cmake_module/env_hook/opensplice.sh.in#L71) is a little overwhelming, it appears during every environment load (e.g. new bash shell) when using a custom OSPL_URI. 

Would you take a PR to remove it? I would think if the user is setting OSPL_URI, they are doing so intentionally.

**Comment by clalancette** [comment]
Up until [recently](https://github.com/ros2/ros2_documentation/pull/105/files), the install instructions were telling the user to always override OSPL_URI.  The combination of that plus the warning are what allowed us to find that problem and fix the documentation for it.

Now that the install documentation is fixed, I personally think that it would be fine to remove the warning, but I'd be interested if anyone else on @ros2/team has a different opinion.

**Comment by wjwwood** [comment]
> Now that the install documentation is fixed, I personally think that it would be fine to remove the warning, but I'd be interested if anyone else on @ros2/team has a different opinion.

Sounds good to me.
