### ISSUE TITLE
when get gid from the Instance handle ,the serial field is fill 0 ?

### ISSUE THREAD

**Issue by reed-lau** [ros2/rosidl_typesupport_opensplice#4]
https://github.com/ros2/rosidl_typesupport_opensplice/blob/5afbb41efb16747127e8746cd29f4925e5fdd2b1/rosidl_typesupport_opensplice_cpp/src/u_instanceHandle.c#L42

I found that you get the gid from the instance handle, but set the seril to ZERO.
when i using opensplice's get_matched_subscription_data/get_matched_publication_data/get_discovered_participant_data or read_instance function, it will retrieve the xxxBuiltinTopicData, and we can get the gid from the BuiltinTopicKey_t key field(in fact, it is a typedef int[3]). it seems that the serial is not ZERO.

how can I match it. or what does the `serial` actual mean. can I just ignore it and only using the first two field of int[3].

**Comment by dirk-thomas** [comment]
The ROS 2 code only initializes the `serial` member in the referenced location. Any changes will likely happen somewhere inside OpenSplice.

Maybe @michielb-adlink or @eboasson have an answer to your question.

**Comment by eboasson** [comment]
@reed-lau, you should ignore `serial` when comparing them. The other two fields together uniquely identify instances/entities, but they can get reused after some time. The `serial` field is a generation counter, which means that the full gid cannot be reused within hours (with current hardware) and typically never gets reused during the lifetime of the system.

Making the instance handle equal to the gid with `serial` chopped off, gives unique instance handles that still fit in a 64-bit integer. Using a standard integral type for the instance handle type is much more convenient than using complex type, as it allows comparing them using the `==` operator in C.

**Comment by reed-lau** [comment]
@eboasson  thanks for your concernning. sometimes, we could see the serial is equal to 0, 1, 2, 3, according to your description, it's the 0th, 1st, 2nd, 3rd generation. When this case occurs, does it mean the 0th generation's gid is used up, will the first two field may collision? What's the total availiable amount of the gid in one system?

**Comment by eboasson** [comment]
It is only reused when the first generation is gone and we also wait some time before we reuse it, so you don't actually have to worry about collisions unless you look across look time spans. Per systemId, there are (from memory) ~2^20 unique ids, but reuse generally doesn't happen until at least ~1000 different gids (not counting `serial`) have been allocated.

Do keep in mind that these are used for entities (like readers and writers) and for instances, but not for individual data samples. In the vast majority of systems the sets of readers and writers in a process, as well as the set of instances published by a writer, are pretty stable. That means the rate at which they are allocated is pretty low and it takes a long time before they get reused. In a ROS2 system, there is by definition only a single instance per writer and you won't see `serial` changing often. (I think it might happen for some things while OpenSplice is starting, but after that it would be pretty rare.)

**Comment by dirk-thomas** [comment]
Assuming the comments answered the original question I will go ahead and close this ticket. Please feel free to continue commenting.
