### ISSUE TITLE
Using $ENV{AMENT_PREFIX_PATH} under Windows leads to CMake error

### ISSUE THREAD

**Issue by Reen** [ros2/rosidl_typesupport_opensplice#47]
Hi,

I was using ros2 eloquent in conjunction with vcpkg. When configuring a simple project, the following line introduced an error somewhere down the `find_package` call:
https://github.com/ros2/rosidl_typesupport_opensplice/blob/c11c3f0b142884954100ad292c201bcb1fe0e9e8/opensplice_cmake_module/cmake/Modules/FindOpenSplice.cmake#L101

The fix for this is as follows:
```cmake
  file(TO_CMAKE_PATH $ENV{AMENT_PREFIX_PATH} AMENT_PREFIX_PATH)
  find_package(opensplice ${quiet} NO_MODULE COMPONENTS CXX
    PATHS ${AMENT_PREFIX_PATH} /usr /usr/local)
```
This will correctly escape the path which, due to Windows, contains backslashes.

Best,
René

**Comment by hidmic** [comment]
@Reen would you be willing to contribute this fix? It'd only apply to Eloquent, as Opensplice packages have been removed since (see https://github.com/ros2/ros2/pull/865 for context).

**Comment by clalancette** [comment]
Closing since we don't support opensplice anymore.
